// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.padding2(/* zero */-789508312, /* `px */[
              25096,
              20
            ]),
        /* [] */0
      ]
    ]);

exports.container = container;
/* container Not a pure module */
