// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.padding2(/* zero */-789508312, /* `px */[
              25096,
              20
            ]),
        /* [] */0
      ]
    ]);

export {
  container ,
  
}
/* container Not a pure module */
