// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";

var RR = /* module */[
  /* statelessComponent */ReasonReact.statelessComponent,
  /* statelessComponentWithRetainedProps */ReasonReact.statelessComponentWithRetainedProps,
  /* reducerComponent */ReasonReact.reducerComponent,
  /* reducerComponentWithRetainedProps */ReasonReact.reducerComponentWithRetainedProps,
  /* element */ReasonReact.element,
  /* wrapReasonForJs */ReasonReact.wrapReasonForJs,
  /* createDomElement */ReasonReact.createDomElement,
  /* wrapJsForReason */ReasonReact.wrapJsForReason,
  /* Router */ReasonReact.Router
];

function s(prim) {
  return prim;
}

var Utils = /* module */[
  /* brand */"ChildCareGoWhere",
  /* title */"Find the best child care centers that suits you in Singapore"
];

var Global_css = 0;

export {
  RR ,
  s ,
  Utils ,
  Global_css ,
  
}
/* ReasonReact Not a pure module */
