// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");

var RR = /* module */[
  /* statelessComponent */ReasonReact.statelessComponent,
  /* statelessComponentWithRetainedProps */ReasonReact.statelessComponentWithRetainedProps,
  /* reducerComponent */ReasonReact.reducerComponent,
  /* reducerComponentWithRetainedProps */ReasonReact.reducerComponentWithRetainedProps,
  /* element */ReasonReact.element,
  /* wrapReasonForJs */ReasonReact.wrapReasonForJs,
  /* createDomElement */ReasonReact.createDomElement,
  /* wrapJsForReason */ReasonReact.wrapJsForReason,
  /* Router */ReasonReact.Router
];

function s(prim) {
  return prim;
}

exports.RR = RR;
exports.s = s;
/* ReasonReact Not a pure module */
