// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function item(json) {
  return /* record */[/* tp_code */Json_decode.field("tp_code", Json_decode.string, json)];
}

var Decode = /* module */[/* item */item];

function result(data) {
  return Json_decode.array(item, data);
}

exports.Decode = Decode;
exports.result = result;
/* No side effect */
