// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function item(json) {
  return /* record */[
          /* tpCode */Json_decode.field("tp_code", Json_decode.string, json),
          /* centreCode */Json_decode.field("centre_code", Json_decode.string, json),
          /* centreName */Json_decode.field("centre_name", Json_decode.string, json),
          /* organisationCode */Json_decode.field("organisation_code", Json_decode.string, json),
          /* organisationDescription */Json_decode.field("organisation_description", Json_decode.string, json),
          /* centreOperatingModel */Json_decode.field("centre_operating_model", Json_decode.string, json),
          /* centreContactNo */Json_decode.field("centre_contact_no", Json_decode.$$int, json),
          /* centreEmailAddress */Json_decode.field("centre_email_address", Json_decode.string, json),
          /* centreAddress */Json_decode.field("centre_address", Json_decode.string, json),
          /* centreWebsite */Json_decode.field("centre_website", Json_decode.string, json),
          /* infantVacancy */Json_decode.field("infant_vacancy", Json_decode.string, json),
          /* pgVacancy */Json_decode.field("pg_vacancy", Json_decode.string, json),
          /* n1Vacancy */Json_decode.field("n1_vacancy", Json_decode.string, json),
          /* n2Vacancy */Json_decode.field("n2_vacancy", Json_decode.string, json),
          /* k1Vacancy */Json_decode.field("k1_vacancy", Json_decode.string, json),
          /* k2Vacancy */Json_decode.field("k2_vacancy", Json_decode.string, json),
          /* foodOffered */Json_decode.field("food_offered", Json_decode.string, json),
          /* secondLanguagesOffered */Json_decode.field("second_languages_offered", Json_decode.string, json),
          /* sparkCertified */Json_decode.field("spark_certified", Json_decode.string, json),
          /* weekdayFullDay */Json_decode.field("weekday_full_day", Json_decode.string, json),
          /* weekdayHalfdayAm */Json_decode.field("weekday_halfday_am", Json_decode.string, json),
          /* weekdayHalfdayPm */Json_decode.field("weekday_halfday_pm", Json_decode.string, json),
          /* saturday */Json_decode.field("saturday", Json_decode.string, json),
          /* schemeType */Json_decode.field("scheme_type", Json_decode.string, json),
          /* extendedOperatingHours */Json_decode.field("extended_operating_hours", Json_decode.string, json),
          /* provisionOfTransport */Json_decode.field("provision_of_transport", Json_decode.string, json),
          /* iccp */Json_decode.field("iccp", Json_decode.string, json),
          /* governmentSubsidy */Json_decode.field("government_subsidy", Json_decode.string, json),
          /* gstRegisration */Json_decode.field("gst_regisration", Json_decode.string, json),
          /* lastUpdated */Json_decode.field("last_updated", Json_decode.string, json),
          /* remarks */Json_decode.field("remarks", Json_decode.string, json)
        ];
}

var Decode = /* module */[/* item */item];

function result(data) {
  return Json_decode.array(item, data);
}

export {
  Decode ,
  result ,
  
}
/* No side effect */
