// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function item(json) {
  return /* record */[
          /* tpCode */Json_decode.field("tp_code", Json_decode.string, json),
          /* centreCode */Json_decode.field("centre_code", Json_decode.string, json),
          /* centreName */Json_decode.field("centre_name", Json_decode.string, json),
          /* organisationCode */Json_decode.field("organisation_code", Json_decode.string, json),
          /* organisationDescription */Json_decode.field("organisation_description", Json_decode.string, json),
          /* centreOperatingModel */Json_decode.field("centre_operating_model", Json_decode.string, json),
          /* centreContactNo */Json_decode.field("centre_contact_no", Json_decode.$$int, json),
          /* centreEmailAddress */Json_decode.field("centre_email_address", Json_decode.string, json)
        ];
}

var Decode = /* module */[/* item */item];

function result(data) {
  return Json_decode.array(item, data);
}

exports.Decode = Decode;
exports.result = result;
/* No side effect */
