// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var header = Emotion.css(undefined, /* :: */[
      Emotion.label("header"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100
            ]),
        /* :: */[
          Emotion.display(/* flex */-1010954439),
          /* :: */[
            Emotion.backgroundColor(/* `rgba */[
                  -878128972,
                  /* tuple */[
                    255,
                    255,
                    255,
                    0.2
                  ]
                ]),
            /* :: */[
              Emotion.minHeight(/* `px */[
                    25096,
                    60
                  ]),
              /* :: */[
                Emotion.borderBottom(/* `px */[
                      25096,
                      1
                    ], /* solid */12956715, /* `rgba */[
                      -878128972,
                      /* tuple */[
                        0,
                        0,
                        0,
                        0.1
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

exports.header = header;
/* header Not a pure module */
