// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var header = Emotion.css(undefined, /* :: */[
      Emotion.label("header"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100
            ]),
        /* :: */[
          Emotion.display(/* flex */-1010954439),
          /* :: */[
            Emotion.minHeight(/* `px */[
                  25096,
                  40
                ]),
            /* :: */[
              Emotion.padding2(/* `px */[
                    25096,
                    10
                  ], /* zero */-789508312),
              /* :: */[
                Emotion.alignItems(/* center */98248149),
                /* :: */[
                  Emotion.position(/* fixed */10615156),
                  /* :: */[
                    Emotion.zIndex(999),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var brand = Emotion.css(undefined, /* :: */[
      Emotion.label("brand"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              18
            ]),
        /* :: */[
          Emotion.fontWeight(700),
          /* :: */[
            Emotion.textDecoration(/* none */-922086728),
            /* :: */[
              Emotion.color(/* `hex */[
                    5194459,
                    "fffb00"
                  ]),
              /* :: */[
                Emotion.textShadow(undefined, /* `px */[
                      25096,
                      1
                    ], /* `px */[
                      25096,
                      1
                    ], /* `rgba */[
                      -878128972,
                      /* tuple */[
                        0,
                        0,
                        0,
                        0.4
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  header ,
  brand ,
  
}
/* header Not a pure module */
