// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Prelude$ReactHooksTemplate = require("../helpers/Prelude.bs.js");
var Header_Css$ReactHooksTemplate = require("./Header_Css.bs.js");

function Header(Props) {
  return React.createElement("div", {
              className: Header_Css$ReactHooksTemplate.header
            }, Prelude$ReactHooksTemplate.s(""));
}

var Css = 0;

var make = Header;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
