// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Prelude$ChildCareCenter = require("../helpers/Prelude.bs.js");
var Header_Css$ChildCareCenter = require("./Header_Css.bs.js");
var GlobalComponentStyle_Css$ChildCareCenter = require("../helpers/GlobalComponentStyle_Css.bs.js");

function Header(Props) {
  return React.createElement("div", {
              className: Header_Css$ChildCareCenter.header
            }, React.createElement("div", {
                  className: GlobalComponentStyle_Css$ChildCareCenter.container
                }, React.createElement("a", {
                      className: Header_Css$ChildCareCenter.brand,
                      href: "/"
                    }, Prelude$ChildCareCenter.s(Prelude$ChildCareCenter.Utils[/* brand */0]))));
}

var Css = 0;

var make = Header;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
