// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Search_Css$ChildCareCenter from "./Search_Css.bs.js";

function Search(Props) {
  return React.createElement("form", undefined, React.createElement("input", {
                  className: Search_Css$ChildCareCenter.input
                }));
}

var Css = 0;

var make = Search;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
