// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var input = Emotion.css(undefined, /* :: */[
      Emotion.label("input"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.marginTop(/* `px */[
                25096,
                60
              ]),
          /* :: */[
            Emotion.borderStyle(/* none */-922086728),
            /* :: */[
              Emotion.width(/* `calc */[
                    -1044768619,
                    /* tuple */[
                      /* sub */5745024,
                      /* `pct */[
                        5591841,
                        100
                      ],
                      /* `px */[
                        25096,
                        40
                      ]
                    ]
                  ]),
              /* :: */[
                Emotion.height(/* `px */[
                      25096,
                      60
                    ]),
                /* :: */[
                  Emotion.borderRadius(/* `px */[
                        25096,
                        3
                      ]),
                  /* :: */[
                    Emotion.backgroundColor(/* `rgba */[
                          -878128972,
                          /* tuple */[
                            255,
                            255,
                            255,
                            0.8
                          ]
                        ]),
                    /* :: */[
                      Emotion.border(/* `px */[
                            25096,
                            1
                          ], /* solid */12956715, /* `rgba */[
                            -878128972,
                            /* tuple */[
                              0,
                              0,
                              0,
                              0.4
                            ]
                          ]),
                      /* :: */[
                        Emotion.outlineStyle(/* none */-922086728),
                        /* :: */[
                          Emotion.boxShadow(undefined, /* `px */[
                                25096,
                                1
                              ], /* `px */[
                                25096,
                                1
                              ], undefined, undefined, /* `rgba */[
                                -878128972,
                                /* tuple */[
                                  0,
                                  0,
                                  0,
                                  0.2
                                ]
                              ]),
                          /* :: */[
                            Emotion.padding2(/* `px */[
                                  25096,
                                  10
                                ], /* `px */[
                                  25096,
                                  20
                                ]),
                            /* :: */[
                              Emotion.fontSize(/* `px */[
                                    25096,
                                    16
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

exports.input = input;
/* input Not a pure module */
