// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Search_Css$ChildCareCenter from "./Search_Css.bs.js";

function Search(Props) {
  var onChange = Props.onChange;
  return React.createElement("form", undefined, React.createElement("input", {
                  className: Search_Css$ChildCareCenter.input,
                  onChange: (function ($$event) {
                      return Curry._1(onChange, $$event.target.value);
                    })
                }));
}

var Css = 0;

var make = Search;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
