// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Search_Css$ChildCareCenter = require("./Search_Css.bs.js");

function Search(Props) {
  return React.createElement("form", undefined, React.createElement("input", {
                  className: Search_Css$ChildCareCenter.input
                }));
}

var Css = 0;

var make = Search;

exports.Css = Css;
exports.make = make;
/* react Not a pure module */
