// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactLeaflet from "react-leaflet";
import * as Header$ChildCareCenter from "./components/Header.bs.js";
import * as Search$ChildCareCenter from "./components/Search.bs.js";
import * as App_Css$ChildCareCenter from "./App_Css.bs.js";
import * as Prelude$ChildCareCenter from "./helpers/Prelude.bs.js";
import * as ChildCareT$ChildCareCenter from "./types/ChildCareT.bs.js";

var initialState = /* record */[
  /* centers : Loading */0,
  /* searchedCenters */undefined,
  /* search */""
];

function reducer(state, action) {
  switch (action.tag | 0) {
    case 0 : 
        return /* record */[
                /* centers */action[0],
                /* searchedCenters */state[/* searchedCenters */1],
                /* search */state[/* search */2]
              ];
    case 1 : 
        return /* record */[
                /* centers */state[/* centers */0],
                /* searchedCenters */state[/* searchedCenters */1],
                /* search */action[0]
              ];
    case 2 : 
        return /* record */[
                /* centers */state[/* centers */0],
                /* searchedCenters */action[0],
                /* search */state[/* search */2]
              ];
    
  }
}

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var match$1 = match[0];
  var search = match$1[/* search */2];
  var searchedCenters = match$1[/* searchedCenters */1];
  var centers = match$1[/* centers */0];
  React.useEffect((function () {
          fetch("/data/childcare.json").then((function (prim) {
                      return prim.json();
                    })).then((function (json) {
                    Curry._1(dispatch, /* CentersLoaded */Block.__(0, [/* Loaded */Block.__(1, [ChildCareT$ChildCareCenter.result(json)])]));
                    return Promise.resolve(/* () */0);
                  })).catch((function (err) {
                  Curry._1(dispatch, /* CentersLoaded */Block.__(0, [/* Failed */Block.__(0, [err])]));
                  return Promise.resolve(/* () */0);
                }));
          return undefined;
        }), ([]));
  React.useEffect((function () {
          if (typeof centers !== "number") {
            if (centers.tag) {
              if (search !== "") {
                Curry._1(dispatch, /* SearchCentersLoaded */Block.__(2, [Belt_Array.keep(centers[0], (function (center) {
                                if (center[/* centreName */2].indexOf(search) >= 1 || center[/* organisationDescription */4].indexOf(search) >= 1) {
                                  return true;
                                } else {
                                  return center[/* centreAddress */8].indexOf(search) >= 1;
                                }
                              }))]));
              } else {
                Curry._1(dispatch, /* SearchCentersLoaded */Block.__(2, [undefined]));
              }
            }
            
          }
          return undefined;
        }), /* array */[search]);
  var tmp;
  if (typeof centers === "number") {
    tmp = null;
  } else if (centers.tag) {
    var centers$1 = centers[0];
    var match$2 = searchedCenters === undefined;
    var centers$2 = match$2 ? centers$1 : Belt_Option.getWithDefault(searchedCenters, centers$1);
    tmp = Belt_Array.map(centers$2, (function (center) {
            return React.createElement("div", {
                        key: center[/* centreCode */1] + center[/* tpCode */0],
                        className: App_Css$ChildCareCenter.center
                      }, React.createElement("h3", {
                            className: App_Css$ChildCareCenter.centerTitle
                          }, Prelude$ChildCareCenter.s(center[/* centreName */2])), React.createElement("div", {
                            className: App_Css$ChildCareCenter.centerContent
                          }, React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* organisationDescription */4])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* centreAddress */8])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* centreWebsite */9])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(String(center[/* centreContactNo */6])))));
          }));
  } else {
    tmp = Prelude$ChildCareCenter.s("Error loading data");
  }
  return React.createElement("div", {
              className: App_Css$ChildCareCenter.app
            }, React.createElement(Header$ChildCareCenter.make, { }), React.createElement("div", {
                  className: App_Css$ChildCareCenter.content
                }, React.createElement("div", {
                      className: App_Css$ChildCareCenter.left
                    }, React.createElement("div", {
                          className: App_Css$ChildCareCenter.title
                        }, Prelude$ChildCareCenter.s(Prelude$ChildCareCenter.Utils[/* title */1])), React.createElement(Search$ChildCareCenter.make, {
                          onChange: (function (value) {
                              return Curry._1(dispatch, /* SearchUpdated */Block.__(1, [value]));
                            })
                        })), React.createElement("div", {
                      className: App_Css$ChildCareCenter.right
                    }, React.createElement("div", {
                          className: App_Css$ChildCareCenter.centers
                        }, tmp))), React.createElement("div", {
                  className: App_Css$ChildCareCenter.map
                }, React.createElement(ReactLeaflet.Map, {
                      center: /* tuple */[
                        1.385270,
                        103.851959
                      ],
                      zoom: 12,
                      children: null
                    }, React.createElement(ReactLeaflet.TileLayer, {
                          url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                          attribution: "&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
                        }), React.createElement(ReactLeaflet.Marker, {
                          position: /* tuple */[
                            51.505,
                            -0.09
                          ],
                          children: React.createElement(ReactLeaflet.Popup, {
                                children: Prelude$ChildCareCenter.s("A pretty CSS3 popup.<br />Easily customizable.")
                              })
                        }))));
}

var Css = 0;

var make = App;

export {
  Css ,
  initialState ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
