// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ReactLeaflet from "react-leaflet";
import * as Header$ChildCareCenter from "./components/Header.bs.js";
import * as Search$ChildCareCenter from "./components/Search.bs.js";
import * as App_Css$ChildCareCenter from "./App_Css.bs.js";
import * as Prelude$ChildCareCenter from "./helpers/Prelude.bs.js";
import * as ChildCareT$ChildCareCenter from "./types/ChildCareT.bs.js";

function App(Props) {
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setChildCareCenters = match[1];
  var childCareCenters = match[0];
  React.useEffect((function () {
          fetch("/data/childcare.json").then((function (prim) {
                      return prim.json();
                    })).then((function (json) {
                    Curry._1(setChildCareCenters, (function (param) {
                            return /* Loaded */[ChildCareT$ChildCareCenter.result(json)];
                          }));
                    return Promise.resolve(/* () */0);
                  })).catch((function (param) {
                  return Promise.resolve(Curry._1(setChildCareCenters, (function (param) {
                                    return /* Loading */0;
                                  })));
                }));
          return undefined;
        }), ([]));
  return React.createElement("div", {
              className: App_Css$ChildCareCenter.app
            }, React.createElement(Header$ChildCareCenter.make, { }), React.createElement("div", {
                  className: App_Css$ChildCareCenter.content
                }, React.createElement("div", {
                      className: App_Css$ChildCareCenter.left
                    }, React.createElement("div", {
                          className: App_Css$ChildCareCenter.title
                        }, Prelude$ChildCareCenter.s(Prelude$ChildCareCenter.Utils[/* title */1])), React.createElement(Search$ChildCareCenter.make, { })), React.createElement("div", {
                      className: App_Css$ChildCareCenter.right
                    }, React.createElement("div", {
                          className: App_Css$ChildCareCenter.centers
                        }, childCareCenters ? Belt_Array.map(childCareCenters[0], (function (center) {
                                  return React.createElement("div", {
                                              key: center[/* centreCode */1] + center[/* tpCode */0],
                                              className: App_Css$ChildCareCenter.center
                                            }, React.createElement("h3", {
                                                  className: App_Css$ChildCareCenter.centerTitle
                                                }, Prelude$ChildCareCenter.s(center[/* centreName */2])), React.createElement("div", {
                                                  className: App_Css$ChildCareCenter.centerContent
                                                }, React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* organisationDescription */4])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* centreAddress */8])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(center[/* centreWebsite */9])), React.createElement("p", undefined, Prelude$ChildCareCenter.s(String(center[/* centreContactNo */6])))));
                                })) : null))), React.createElement("div", {
                  className: App_Css$ChildCareCenter.map
                }, React.createElement(ReactLeaflet.Map, {
                      center: /* tuple */[
                        1.385270,
                        103.851959
                      ],
                      zoom: 12,
                      children: null
                    }, React.createElement(ReactLeaflet.TileLayer, {
                          url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                          attribution: "&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
                        }), React.createElement(ReactLeaflet.Marker, {
                          position: /* tuple */[
                            51.505,
                            -0.09
                          ],
                          children: React.createElement(ReactLeaflet.Popup, {
                                children: Prelude$ChildCareCenter.s("A pretty CSS3 popup.<br />Easily customizable.")
                              })
                        }))));
}

var Css = 0;

var make = App;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
