// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.flexDirection(/* column */-963948842),
          /* :: */[
            Emotion.height(/* `pct */[
                  5591841,
                  100
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.position(/* fixed */10615156),
        /* :: */[
          Emotion.zIndex(999),
          /* :: */[
            Emotion.fontSize(/* `px */[
                  25096,
                  48
                ]),
            /* :: */[
              Emotion.maxWidth(/* `px */[
                    25096,
                    700
                  ]),
              /* :: */[
                Emotion.fontWeight(700),
                /* :: */[
                  Emotion.top(/* `px */[
                        25096,
                        100
                      ]),
                  /* :: */[
                    Emotion.left(/* `px */[
                          25096,
                          20
                        ]),
                    /* :: */[
                      Emotion.color(/* `hex */[
                            5194459,
                            "fff"
                          ]),
                      /* :: */[
                        Emotion.lineHeight(/* `px */[
                              25096,
                              48
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var content = Emotion.css(undefined, /* :: */[
      Emotion.label("content"),
      /* :: */[
        Emotion.flex(/* `some */[
              -866639116,
              /* tuple */[
                1,
                1,
                /* `pct */[
                  5591841,
                  100
                ]
              ]
            ]),
        /* :: */[
          Emotion.overflow(/* hidden */-862584982),
          /* :: */[
            Emotion.select(".leaflet-container", /* :: */[
                  Emotion.height(/* `pct */[
                        5591841,
                        100
                      ]),
                  /* :: */[
                    Emotion.filters(/* :: */[
                          /* `hueRotate */[
                            1036870963,
                            /* `deg */[
                              4995526,
                              -30
                            ]
                          ],
                          /* :: */[
                            /* `contrast */[
                              934407426,
                              /* `pct */[
                                5591841,
                                60
                              ]
                            ],
                            /* [] */0
                          ]
                        ]),
                    /* [] */0
                  ]
                ]),
            /* :: */[
              Emotion.select(".leaflet-top.leaflet-left", /* :: */[
                    Emotion.top(/* `px */[
                          25096,
                          90
                        ]),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.app = app;
exports.title = title;
exports.content = content;
/* app Not a pure module */
