// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.flexDirection(/* column */-963948842),
          /* :: */[
            Emotion.height(/* `pct */[
                  5591841,
                  100
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              48
            ]),
        /* :: */[
          Emotion.maxWidth(/* `px */[
                25096,
                700
              ]),
          /* :: */[
            Emotion.fontWeight(700),
            /* :: */[
              Emotion.top(/* `px */[
                    25096,
                    100
                  ]),
              /* :: */[
                Emotion.left(/* `px */[
                      25096,
                      20
                    ]),
                /* :: */[
                  Emotion.color(/* `hex */[
                        5194459,
                        "fff"
                      ]),
                  /* :: */[
                    Emotion.lineHeight(/* `px */[
                          25096,
                          48
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var content = Emotion.css(undefined, /* :: */[
      Emotion.label("content"),
      /* :: */[
        Emotion.position(/* fixed */10615156),
        /* :: */[
          Emotion.zIndex(999),
          /* :: */[
            Emotion.width(/* `calc */[
                  -1044768619,
                  /* tuple */[
                    /* sub */5745024,
                    /* `pct */[
                      5591841,
                      100
                    ],
                    /* `px */[
                      25096,
                      40
                    ]
                  ]
                ]),
            /* :: */[
              Emotion.marginLeft(/* `px */[
                    25096,
                    20
                  ]),
              /* :: */[
                Emotion.marginRight(/* `px */[
                      25096,
                      20
                    ]),
                /* :: */[
                  Emotion.top(/* `px */[
                        25096,
                        100
                      ]),
                  /* :: */[
                    Emotion.lineHeight(/* `px */[
                          25096,
                          48
                        ]),
                    /* :: */[
                      Emotion.display(/* flex */-1010954439),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var left = Emotion.css(undefined, /* :: */[
      Emotion.label("left"),
      /* :: */[
        Emotion.color(/* `hex */[
              5194459,
              "fff"
            ]),
        /* :: */[
          Emotion.maxWidth(/* `pct */[
                5591841,
                50
              ]),
          /* :: */[
            Emotion.fontSize(/* `px */[
                  25096,
                  48
                ]),
            /* :: */[
              Emotion.fontWeight(700),
              /* :: */[
                Emotion.textShadow(undefined, /* `px */[
                      25096,
                      1
                    ], /* `px */[
                      25096,
                      1
                    ], /* `rgba */[
                      -878128972,
                      /* tuple */[
                        0,
                        0,
                        0,
                        0.4
                      ]
                    ]),
                /* :: */[
                  Emotion.paddingRight(/* `px */[
                        25096,
                        20
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var right = Emotion.css(undefined, /* :: */[
      Emotion.label("right"),
      /* :: */[
        Emotion.paddingLeft(/* `px */[
              25096,
              20
            ]),
        /* :: */[
          Emotion.flex(/* `some */[
                -866639116,
                /* tuple */[
                  1,
                  1,
                  /* auto */-1065951377
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

var map = Emotion.css(undefined, /* :: */[
      Emotion.label("map"),
      /* :: */[
        Emotion.flex(/* `some */[
              -866639116,
              /* tuple */[
                1,
                1,
                /* `pct */[
                  5591841,
                  100
                ]
              ]
            ]),
        /* :: */[
          Emotion.overflow(/* hidden */-862584982),
          /* :: */[
            Emotion.select(".leaflet-container", /* :: */[
                  Emotion.height(/* `pct */[
                        5591841,
                        100
                      ]),
                  /* :: */[
                    Emotion.filters(/* :: */[
                          /* `hueRotate */[
                            1036870963,
                            /* `deg */[
                              4995526,
                              -30
                            ]
                          ],
                          /* :: */[
                            /* `contrast */[
                              934407426,
                              /* `pct */[
                                5591841,
                                60
                              ]
                            ],
                            /* [] */0
                          ]
                        ]),
                    /* [] */0
                  ]
                ]),
            /* :: */[
              Emotion.select(".leaflet-top.leaflet-left", /* :: */[
                    Emotion.top(/* `px */[
                          25096,
                          90
                        ]),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var centers = Emotion.css(undefined, /* :: */[
      Emotion.label("centers"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100
            ]),
        /* :: */[
          Emotion.height(/* `pct */[
                5591841,
                100
              ]),
          /* :: */[
            Emotion.display(/* block */888960333),
            /* :: */[
              Emotion.zIndex(9),
              /* :: */[
                Emotion.fontSize(/* `px */[
                      25096,
                      16
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var center = Emotion.css(undefined, /* :: */[
      Emotion.label("center"),
      /* :: */[
        Emotion.backgroundColor(/* `rgba */[
              -878128972,
              /* tuple */[
                255,
                255,
                255,
                0.8
              ]
            ]),
        /* :: */[
          Emotion.padding2(/* `px */[
                25096,
                20
              ], /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.borderRadius(/* `px */[
                  25096,
                  3
                ]),
            /* :: */[
              Emotion.marginBottom(/* `px */[
                    25096,
                    10
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.app = app;
exports.title = title;
exports.content = content;
exports.left = left;
exports.right = right;
exports.map = map;
exports.centers = centers;
exports.center = center;
/* app Not a pure module */
