// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

Emotion.$$global("html, body", /* :: */[
      Emotion.fontFamily("B612 Mono, monospace"),
      /* :: */[
        Emotion.padding(/* zero */-789508312),
        /* :: */[
          Emotion.margin(/* zero */-789508312),
          /* :: */[
            Emotion.minHeight(/* `pct */[
                  5591841,
                  100
                ]),
            /* :: */[
              Emotion.height(/* `pct */[
                    5591841,
                    100
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

Emotion.$$global("#app", /* :: */[
      Emotion.minHeight(/* `pct */[
            5591841,
            100
          ]),
      /* :: */[
        Emotion.height(/* `pct */[
              5591841,
              100
            ]),
        /* [] */0
      ]
    ]);

export {
  
}
/*  Not a pure module */
