// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

Emotion.$$global("html, body", /* :: */[
      Emotion.fontFamily("B612 Mono, monospace"),
      /* :: */[
        Emotion.padding(/* zero */-789508312),
        /* :: */[
          Emotion.margin(/* zero */-789508312),
          /* [] */0
        ]
      ]
    ]);

/*  Not a pure module */
