// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$ChildCareCenter from "./App.bs.js";
import * as GlobalStyles$ChildCareCenter from "./GlobalStyles.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$ChildCareCenter.make, { }), "app");

export {
  
}
/*  Not a pure module */
